### PR TITLE
Zh cn translation feature

### PR DESCRIPTION
**Pull request by Z-Shang**
Soundtrack of this PR: [link to song that really fits the mood of this PR]()

### Motivation

To initialise the Simplified Chinese translation

### In this PR

Translated the text from English to Simplified Chinese in `/locales/zhCN/translation.json`, as well as added `zhCN` into the languages field of the English version.

### Future Work

Once the English text is updated, this will need some redo

### CODE REVIEW

**Comment by BrianCorbin** [comment]
Added implementation of the language to the language selection menu, and changed base to the full-service-integration branch.

**Comment by BrianCorbin** [comment]
Thank you for these translations! ✨

**Comment by Z-Shang** [comment]
no worries 👍

**Review by davidyhall — APPROVED** [review]
:shipit:

**Pull request merged**
