### PR TITLE
Send MOB Confirmation revision

### PR DESCRIPTION
**Pull request by johnedma**
Soundtrack of this PR: [Foe Tha Love of $ · Eazy-E · Bone Thugs-n-Harmony](https://www.youtube.com/watch?v=X8hAnEaY-bM)

### Motivation :money_mouth_face:

Reviewing various component in an attempt to improve aesthetic of app and overall user experience.

### In this PR

- lastLineClass prop added to LongCode for easier manipulation
- modified spacing and alignment of components within confirmation modal

### Future Work

- Continued components reviews and revisions for possible UI/UX improvements 

### Screen Shots

| Screen Name                                             | Before | After |
| :------------------------------------------------------ | :----: | :---: |
| SendMobForm |Screen Shot 2021-03-09 at 6 38 50 PM|Screen Shot 2021-03-09 at 6 38 15 PM|

### Testing
CircleCI Approves :heavy_check_mark:

### CODE REVIEW

**Comment by johnedma** [comment]
> How does this look when you grow it to a large size, still following the same positioning as it scales?

max screen 15-inch
Screen Shot 2021-03-10 at 8 43 54 AM

**Review by BrianCorbin — APPROVED** [review]

**Review by BrianCorbin — COMMENTED** [review]
Cool, let's wait until David is done with integrating Full Service to pull this :)

**Comment by johnedma** [comment]
> Cool, let's wait until David is done with integrating Full Service to pull this :)

Definitely, David is always the one to pull the trigger on my PR's. Appreciate the review tho :+1:

**Comment by fktt22** [comment]
QUESTION: do we have a story (Storybook's) for this?

**Review by fktt22 — APPROVED** [review]

**Pull request merged**
